# Generated by Django 3.1.7 on 2021-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('profile_picutre', models.ImageField(upload_to='')),
                ('mobile_phone', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
