# Generated by Django 3.1.7 on 2021-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picutre',
            field=models.ImageField(blank=True, null=True, upload_to='users_images/'),
        ),
    ]
