# Generated by Django 3.1.7 on 2021-04-07 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedComment',
            fields=[
                ('report_count', models.IntegerField(default=1)),
                ('report_message', models.TextField()),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='comments.comments')),
            ],
        ),
    ]
