# Generated by Django 3.1.7 on 2021-03-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcomment',
            name='report_count',
            field=models.IntegerField(default=1),
        ),
    ]
