# Generated by Django 3.1.7 on 2021-03-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210331_1851'),
        ('comments', '0003_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportedcomment',
            name='report_message',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
