# Generated by Django 3.1.7 on 2021-03-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210331_1851'),
        ('projects', '0002_projects_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_target',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
