# Generated by Django 3.1.7 on 2021-04-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210331_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedProject',
            fields=[
                ('report_count', models.IntegerField(default=0)),
                ('report_message', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.projects')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='id',
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.projects'),
        ),
    ]
