# Generated by Django 3.1.7 on 2021-04-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210403_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedProject',
            fields=[
                ('report_count', models.IntegerField(default=0)),
                ('report_message', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.projects')),
            ],
        ),
    ]
