# Generated by Django 3.1.7 on 2021-04-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210404_0951'),
        ('projects', '0004_auto_20210403_1928'),
    ]

    operations = [
    ]
