# Generated by Django 3.1.7 on 2021-04-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_reportedproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='five_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='four_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='one_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='three_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='two_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
