# Generated by Django 3.1.7 on 2021-04-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_merge_20210405_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
